name: Checkmarx Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkmarx_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Checkmarx CLI
        run: |
          curl -L https://github.com/checkmarx-ts/checkmarx-cli/releases/download/v2.0.0/cx-cli-linux-x64.zip -o cx-cli.zip
          unzip cx-cli.zip -d cx-cli
          sudo mv cx-cli/cx-cli /usr/local/bin/
          # Ensure the CLI was installed correctly
          cx-cli --version
      - name: Run Checkmarx Scan
        run: |
          cx-cli scan --project RepoWebGoat_Test